CREATE TABLE IF NOT EXISTS data (
  col1 INTEGER PRIMARY KEY,
  col2 varchar(200) NOT NULL,
  col3 varchar(200) NOT NULL,
  col4 INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS data_column_description (
  id INTEGER PRIMARY KEY,
  col_name varchar(200) NOT NULL,
  col_type varchar(50) NOT NULL, 
  match_level INTEGER NOT NULL
);

INSERT INTO data_column_description (id, col_name, col_type, match_level) VALUES (1, 'Id', 'id', 0);
INSERT INTO data_column_description (id, col_name, col_type, match_level) VALUES (2, 'College', 'data', 1);
INSERT INTO data_column_description (id, col_name, col_type, match_level) VALUES (3, 'Campus', 'location', 2);
INSERT INTO data_column_description (id, col_name, col_type, match_level) VALUES (4, 'Rank', 'data', 2);

CREATE TABLE IF NOT EXISTS alias (
  id INTEGER PRIMARY KEY,
  data_id INTEGER NOT NULL,
  alias_name varchar(200) NOT NULL,
  FOREIGN KEY (data_id) REFERENCES data(id)
);

CREATE TABLE IF NOT EXISTS description (
  name varchar(200) NOT NULL,
  description varchar(200) NOT NULL
);

INSERT INTO description (name, description) VALUES ('data', 'Contains the Top 100 US Colleges of 2011 as ranked by USNews');

INSERT INTO data (col2, col3, col4) VALUES ('Harvard University', 'Harvard University', 1);
INSERT INTO data (col2, col3, col4) VALUES ('Princeton University', 'Princeton University', 2);
INSERT INTO data (col2, col3, col4) VALUES ('Yale University', 'Yale University', 3);
INSERT INTO data (col2, col3, col4) VALUES ('Columbia University', 'Columbia University', 4);
INSERT INTO data (col2, col3, col4) VALUES ('California Institute of Technology', 'California Institute of Technology', 5);
INSERT INTO data (col2, col3, col4) VALUES ('Massachusetts Institute of Technology', 'Massachusetts Institute of Technology', 5);
INSERT INTO data (col2, col3, col4) VALUES ('Stanford University', 'Stanford University', 5);
INSERT INTO data (col2, col3, col4) VALUES ('University of Chicago', 'University of Chicago', 5);
INSERT INTO data (col2, col3, col4) VALUES ('University of Pennsylvania', 'University of Pennsylvania', 5);
INSERT INTO data (col2, col3, col4) VALUES ('Duke University', 'Duke University', 10);
INSERT INTO data (col2, col3, col4) VALUES ('Dartmouth College', 'Dartmouth College', 11);
INSERT INTO data (col2, col3, col4) VALUES ('Northwestern University', 'Northwestern University', 12);
INSERT INTO data (col2, col3, col4) VALUES ('Johns Hopkins University', 'Johns Hopkins University', 13);
INSERT INTO data (col2, col3, col4) VALUES ('Washington University in St. Louis', 'Washington University in St. Louis', 14);
INSERT INTO data (col2, col3, col4) VALUES ('Brown University', 'Brown University', 15);
INSERT INTO data (col2, col3, col4) VALUES ('Cornell University', 'Cornell University', 16);
INSERT INTO data (col2, col3, col4) VALUES ('Rice University', 'Rice University', 17);
INSERT INTO data (col2, col3, col4) VALUES ('Vanderbilt University', 'Vanderbilt University', 17);
INSERT INTO data (col2, col3, col4) VALUES ('University of Notre Dame', 'University of Notre Dame', 19);
INSERT INTO data (col2, col3, col4) VALUES ('Emory University', 'Emory University', 20);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Berkeley', 'University of California at Berkeley', 21);
INSERT INTO data (col2, col3, col4) VALUES ('Georgetown University', 'Georgetown University', 22);
INSERT INTO data (col2, col3, col4) VALUES ('Carnegie Mellon University', 'Carnegie Mellon University', 23);
INSERT INTO data (col2, col3, col4) VALUES ('University of Southern California', 'University of Southern California', 23);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Los Angeles', 'University of California at Los Angeles', 25);
INSERT INTO data (col2, col3, col4) VALUES ('University of Virginia', 'University of Virginia', 25);
INSERT INTO data (col2, col3, col4) VALUES ('Wake Forest University', 'Wake Forest University', 25);
INSERT INTO data (col2, col3, col4) VALUES ('University of Michigan', 'University of Michigan', 28);
INSERT INTO data (col2, col3, col4) VALUES ('Tufts University', 'Tufts University', 29);
INSERT INTO data (col2, col3, col4) VALUES ('University of North Carolina at Chapel Hill', 'University of North Carolina at Chapel Hill', 29);
INSERT INTO data (col2, col3, col4) VALUES ('Boston College', 'Boston College', 31);
INSERT INTO data (col2, col3, col4) VALUES ('Brandeis University', 'Brandeis University', 31);
INSERT INTO data (col2, col3, col4) VALUES ('College of William and Mary', 'College of William and Mary', 33);
INSERT INTO data (col2, col3, col4) VALUES ('New York University', 'New York University', 33);
INSERT INTO data (col2, col3, col4) VALUES ('University of Rochester', 'University of Rochester', 35);
INSERT INTO data (col2, col3, col4) VALUES ('Georgia Institute of Technology', 'Georgia Institute of Technology', 36);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at San Diego', 'University of California at San Diego', 37);
INSERT INTO data (col2, col3, col4) VALUES ('Case Western Reserve University', 'Case Western Reserve University', 38);
INSERT INTO data (col2, col3, col4) VALUES ('Lehigh University', 'Lehigh University', 38);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Davis', 'University of California at Davis', 38);
INSERT INTO data (col2, col3, col4) VALUES ('University of Miami', 'University of Miami', 38);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Santa Barbara', 'University of California at Santa Barbara', 42);
INSERT INTO data (col2, col3, col4) VALUES ('University of Washington', 'University of Washington', 42);
INSERT INTO data (col2, col3, col4) VALUES ('University of Wisconsin', 'University of Wisconsin', 42);
INSERT INTO data (col2, col3, col4) VALUES ('Penn State University', 'Penn State University', 45);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Irvine', 'University of California at Irvine', 45);
INSERT INTO data (col2, col3, col4) VALUES ('University of Illinois at Urbana-Champaign', 'University of Illinois at Urbana-Champaign', 45);
INSERT INTO data (col2, col3, col4) VALUES ('University of Texas at Austin', 'University of Texas at Austin', 45);
INSERT INTO data (col2, col3, col4) VALUES ('Yeshiva University', 'Yeshiva University', 45);
INSERT INTO data (col2, col3, col4) VALUES ('George Washington University', 'George Washington University', 50);
INSERT INTO data (col2, col3, col4) VALUES ('Rensselaer Polytechnic Institute', 'Rensselaer Polytechnic Institute', 50);
INSERT INTO data (col2, col3, col4) VALUES ('Tulane University', 'Tulane University', 50);
INSERT INTO data (col2, col3, col4) VALUES ('Boston University', 'Boston University', 53);
INSERT INTO data (col2, col3, col4) VALUES ('Fordham University', 'Fordham University', 53);
INSERT INTO data (col2, col3, col4) VALUES ('Ohio State University', 'Ohio State University', 55);
INSERT INTO data (col2, col3, col4) VALUES ('Pepperdine University', 'Pepperdine University', 55);
INSERT INTO data (col2, col3, col4) VALUES ('University of Maryland', 'University of Maryland', 55);
INSERT INTO data (col2, col3, col4) VALUES ('Texas A&M University', 'Texas A&M University', 58);
INSERT INTO data (col2, col3, col4) VALUES ('University of Connecticut', 'University of Connecticut', 58);
INSERT INTO data (col2, col3, col4) VALUES ('University of Florida', 'University of Florida', 58);
INSERT INTO data (col2, col3, col4) VALUES ('University of Pittsburgh', 'University of Pittsburgh', 58);
INSERT INTO data (col2, col3, col4) VALUES ('Northeastern University', 'Northeastern University', 62);
INSERT INTO data (col2, col3, col4) VALUES ('Purdue University', 'Purdue University', 62);
INSERT INTO data (col2, col3, col4) VALUES ('Southern Methodist University', 'Southern Methodist University', 62);
INSERT INTO data (col2, col3, col4) VALUES ('Syracuse University', 'Syracuse University', 62);
INSERT INTO data (col2, col3, col4) VALUES ('University of Georgia', 'University of Georgia', 62);
INSERT INTO data (col2, col3, col4) VALUES ('Worcester Polytechnic Institute', 'Worcester Polytechnic Institute', 62);
INSERT INTO data (col2, col3, col4) VALUES ('Clemson University', 'Clemson University', 68);
INSERT INTO data (col2, col3, col4) VALUES ('Rutgers University', 'Rutgers University', 68);
INSERT INTO data (col2, col3, col4) VALUES ('University of Minnesota', 'University of Minnesota', 68);
INSERT INTO data (col2, col3, col4) VALUES ('Brigham Young University', 'Brigham Young University', 71);
INSERT INTO data (col2, col3, col4) VALUES ('Michigan State University', 'Michigan State University', 71);
INSERT INTO data (col2, col3, col4) VALUES ('University of Iowa', 'University of Iowa', 71);
INSERT INTO data (col2, col3, col4) VALUES 
('Virginia Polytechnic Institute and State University', 'Virginia Polytechnic Institute and State University', 71);
INSERT INTO data (col2, col3, col4) VALUES ('Baylor University', 'Baylor University', 75);
INSERT INTO data (col2, col3, col4) VALUES ('Colorado School of Mines', 'Colorado School of Mines', 75);
INSERT INTO data (col2, col3, col4) VALUES ('Indiana University Bloomington', 'Indiana University Bloomington', 75);
INSERT INTO data (col2, col3, col4) VALUES ('University of Alabama', 'University of Alabama', 75);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Santa Cruz', 'University of California at Santa Cruz', 75);
INSERT INTO data (col2, col3, col4) VALUES ('University of Delaware', 'University of Delaware', 75);
INSERT INTO data (col2, col3, col4) VALUES ('University of Tulsa', 'University of Tulsa', 75);
INSERT INTO data (col2, col3, col4) VALUES ('American University', 'American University', 82);
INSERT INTO data (col2, col3, col4) VALUES ('Auburn University', 'Auburn University', 82);
INSERT INTO data (col2, col3, col4) VALUES ('Marquette University', 'Marquette University', 82);
INSERT INTO data (col2, col3, col4) VALUES ('State University of New York College of Environmental Science and Forestry', 'State University of New York College of Environmental Science and Forestry', 82);
INSERT INTO data (col2, col3, col4) VALUES ('University of Denver', 'University of Denver', 82);
INSERT INTO data (col2, col3, col4) VALUES ('University of Vermont', 'University of Vermont', 82);
INSERT INTO data (col2, col3, col4) VALUES ('Drexel University', 'Drexel University', 88);
INSERT INTO data (col2, col3, col4) VALUES ('Stevens Institute of Technology', 'Stevens Institute of Technology', 88);
INSERT INTO data (col2, col3, col4) VALUES ('Binghamton University', 'Binghamton University', 90);
INSERT INTO data (col2, col3, col4) VALUES ('Miami University', 'Miami University', 90);
INSERT INTO data (col2, col3, col4) VALUES ('Saint Louis University', 'Saint Louis University', 90);
INSERT INTO data (col2, col3, col4) VALUES ('University of Missouri', 'University of Missouri', 90);
INSERT INTO data (col2, col3, col4) VALUES ('Clark University', 'Clark University', 94);
INSERT INTO data (col2, col3, col4) VALUES ('University of Colorado at Boulder', 'University of Colorado at Boulder', 94);
INSERT INTO data (col2, col3, col4) VALUES ('University of Massachusetts Amherst', 'University of Massachusetts Amherst', 94);
INSERT INTO data (col2, col3, col4) VALUES ('Iowa State University', 'Iowa State University', 97);
INSERT INTO data (col2, col3, col4) VALUES ('Texas Christian University', 'Texas Christian University', 97);
INSERT INTO data (col2, col3, col4) VALUES ('University of California at Riverside', 'University of California at Riverside', 97);
INSERT INTO data (col2, col3, col4) VALUES ('University of San Diego', 'University of San Diego', 97);

INSERT INTO alias (data_id, alias_name) VALUES (1, 'Harvard');
INSERT INTO alias (data_id, alias_name) VALUES (2, 'Princeton');
INSERT INTO alias (data_id, alias_name) VALUES (3, 'Yale');
INSERT INTO alias (data_id, alias_name) VALUES (4, 'Columbia');
INSERT INTO alias (data_id, alias_name) VALUES (5, 'Caltech');
INSERT INTO alias (data_id, alias_name) VALUES (6, 'MIT');
INSERT INTO alias (data_id, alias_name) VALUES (6, 'M.I.T.');
INSERT INTO alias (data_id, alias_name) VALUES (7, 'Leland Stanford Junior University');
INSERT INTO alias (data_id, alias_name) VALUES (7, 'Stanford');
INSERT INTO alias (data_id, alias_name) VALUES (8, 'U of C');
INSERT INTO alias (data_id, alias_name) VALUES (8, 'UC');
INSERT INTO alias (data_id, alias_name) VALUES (8, 'UChicago');
INSERT INTO alias (data_id, alias_name) VALUES (8, 'Chicago');
INSERT INTO alias (data_id, alias_name) VALUES (9, 'Penn');
INSERT INTO alias (data_id, alias_name) VALUES (9, 'UPenn');
INSERT INTO alias (data_id, alias_name) VALUES (10, 'Duke');
INSERT INTO alias (data_id, alias_name) VALUES (10, 'Blue Devils');
INSERT INTO alias (data_id, alias_name) VALUES (11, 'Dartmouth');
INSERT INTO alias (data_id, alias_name) VALUES (12, 'Northwestern');
INSERT INTO alias (data_id, alias_name) VALUES (12, 'Wildcats');
INSERT INTO alias (data_id, alias_name) VALUES (13, 'Johns Hopkins');
INSERT INTO alias (data_id, alias_name) VALUES (13, 'JHU');
INSERT INTO alias (data_id, alias_name) VALUES (13, 'Hopkins');
INSERT INTO alias (data_id, alias_name) VALUES (14, 'Washington University');
INSERT INTO alias (data_id, alias_name) VALUES (14, 'Wash U');
INSERT INTO alias (data_id, alias_name) VALUES (14, 'WUSTL');
INSERT INTO alias (data_id, alias_name) VALUES (15, 'Brown');
INSERT INTO alias (data_id, alias_name) VALUES (16, 'Cornell');
INSERT INTO alias (data_id, alias_name) VALUES (17, 'William Marsh Rice University');
INSERT INTO alias (data_id, alias_name) VALUES (17, 'Rice');
INSERT INTO alias (data_id, alias_name) VALUES (18, 'Vanderbilt');
INSERT INTO alias (data_id, alias_name) VALUES (18, 'Vandy');
INSERT INTO alias (data_id, alias_name) VALUES (19, 'University of Notre Dame du Lac');
INSERT INTO alias (data_id, alias_name) VALUES (19, 'Notre Dame');
INSERT INTO alias (data_id, alias_name) VALUES (20, 'Emory');
INSERT INTO alias (data_id, alias_name) VALUES (21, 'University of California, Berkeley');
INSERT INTO alias (data_id, alias_name) VALUES (21, 'UC Berkeley');
INSERT INTO alias (data_id, alias_name) VALUES (21, 'Berkeley, California');
INSERT INTO alias (data_id, alias_name) VALUES (21, 'Berkeley');
INSERT INTO alias (data_id, alias_name) VALUES (21, 'Cal');
INSERT INTO alias (data_id, alias_name) VALUES (22, 'Georgetown');
INSERT INTO alias (data_id, alias_name) VALUES (23, 'Carnegie Mellon');
INSERT INTO alias (data_id, alias_name) VALUES (23, 'CMU');
INSERT INTO alias (data_id, alias_name) VALUES (24, 'USC');
INSERT INTO alias (data_id, alias_name) VALUES (25, 'University of California, Los Angeles');
INSERT INTO alias (data_id, alias_name) VALUES (25, 'UCLA');
INSERT INTO alias (data_id, alias_name) VALUES (26, 'UVA');
INSERT INTO alias (data_id, alias_name) VALUES (26, 'Virginia');
INSERT INTO alias (data_id, alias_name) VALUES (26, 'Cavaliers');
INSERT INTO alias (data_id, alias_name) VALUES (26, 'Cavs');
INSERT INTO alias (data_id, alias_name) VALUES (27, 'Wake Forest');
INSERT INTO alias (data_id, alias_name) VALUES (28, 'Michigan');
INSERT INTO alias (data_id, alias_name) VALUES (28, 'U-M');
INSERT INTO alias (data_id, alias_name) VALUES (28, 'UMich');
INSERT INTO alias (data_id, alias_name) VALUES (28, 'U of M');
INSERT INTO alias (data_id, alias_name) VALUES (29, 'Tufts');
INSERT INTO alias (data_id, alias_name) VALUES (30, 'University of North Carolina');
INSERT INTO alias (data_id, alias_name) VALUES (30, 'UNC');
INSERT INTO alias (data_id, alias_name) VALUES (30, 'UNC-Chapel Hill');
INSERT INTO alias (data_id, alias_name) VALUES (30, 'Chapel Hill');
INSERT INTO alias (data_id, alias_name) VALUES (30, 'North Carolina');
INSERT INTO alias (data_id, alias_name) VALUES (30, 'Carolina');
INSERT INTO alias (data_id, alias_name) VALUES (31, 'BC');
INSERT INTO alias (data_id, alias_name) VALUES (32, 'Brandeis');
INSERT INTO alias (data_id, alias_name) VALUES (33, 'The College of William & Mary in Virginia');
INSERT INTO alias (data_id, alias_name) VALUES (33, 'The College');
INSERT INTO alias (data_id, alias_name) VALUES (33, 'William & Mary');
INSERT INTO alias (data_id, alias_name) VALUES (33, 'W&M');
INSERT INTO alias (data_id, alias_name) VALUES (34, 'NYU');
INSERT INTO alias (data_id, alias_name) VALUES (35, 'U of R');
INSERT INTO alias (data_id, alias_name) VALUES (35, 'UR');
INSERT INTO alias (data_id, alias_name) VALUES (36, 'Georgia Tech');
INSERT INTO alias (data_id, alias_name) VALUES (36, 'Tech');
INSERT INTO alias (data_id, alias_name) VALUES (36, 'GT');
INSERT INTO alias (data_id, alias_name) VALUES (37, 'University of California, San Diego');
INSERT INTO alias (data_id, alias_name) VALUES (37, 'UCSD');
INSERT INTO alias (data_id, alias_name) VALUES (37, 'UC San Diego');
INSERT INTO alias (data_id, alias_name) VALUES (38, 'Case Western Reserve');
INSERT INTO alias (data_id, alias_name) VALUES (38, 'Case Western');
INSERT INTO alias (data_id, alias_name) VALUES (38, 'Case');
INSERT INTO alias (data_id, alias_name) VALUES (38, 'Reserve');
INSERT INTO alias (data_id, alias_name) VALUES (38, 'CWRU');
INSERT INTO alias (data_id, alias_name) VALUES (39, 'Lehigh');
INSERT INTO alias (data_id, alias_name) VALUES (40, 'University of California, Davis');
INSERT INTO alias (data_id, alias_name) VALUES (40, 'UCD');
INSERT INTO alias (data_id, alias_name) VALUES (40, 'UC Davis');
INSERT INTO alias (data_id, alias_name) VALUES (40, 'Davis');
INSERT INTO alias (data_id, alias_name) VALUES (41, 'UM');
INSERT INTO alias (data_id, alias_name) VALUES (41, 'U of M');
INSERT INTO alias (data_id, alias_name) VALUES (41, 'U Miami');
INSERT INTO alias (data_id, alias_name) VALUES (41, 'Miami');
INSERT INTO alias (data_id, alias_name) VALUES (41, 'The U');
INSERT INTO alias (data_id, alias_name) VALUES (42, 'University of California, Santa Barbara');
INSERT INTO alias (data_id, alias_name) VALUES (42, 'UCSB');
INSERT INTO alias (data_id, alias_name) VALUES (42, 'UC Santa Barbara');
INSERT INTO alias (data_id, alias_name) VALUES (43, 'UW');
INSERT INTO alias (data_id, alias_name) VALUES (44, 'University of Wisconsin–Madison');
INSERT INTO alias (data_id, alias_name) VALUES (44, 'Wisconsin');
INSERT INTO alias (data_id, alias_name) VALUES (44, 'UW–Madison');
INSERT INTO alias (data_id, alias_name) VALUES (44, 'Madison');
INSERT INTO alias (data_id, alias_name) VALUES (45, 'Pennsylvania State University');
INSERT INTO alias (data_id, alias_name) VALUES (45, 'Penn St.');
INSERT INTO alias (data_id, alias_name) VALUES (45, 'Penn State');
INSERT INTO alias (data_id, alias_name) VALUES (45, 'PSU');
INSERT INTO alias (data_id, alias_name) VALUES (46, 'University of California, Irvine');
INSERT INTO alias (data_id, alias_name) VALUES (46, 'UCI');
INSERT INTO alias (data_id, alias_name) VALUES (46, 'UC Irvine');
INSERT INTO alias (data_id, alias_name) VALUES (46, 'Irvine');
INSERT INTO alias (data_id, alias_name) VALUES (47, 'University of Illinois');
INSERT INTO alias (data_id, alias_name) VALUES (47, 'U of I');
INSERT INTO alias (data_id, alias_name) VALUES (47, 'UIUC');
INSERT INTO alias (data_id, alias_name) VALUES (47, 'Illinois');
INSERT INTO alias (data_id, alias_name) VALUES (47, 'Illini');
INSERT INTO alias (data_id, alias_name) VALUES (48, 'University of Texas');
INSERT INTO alias (data_id, alias_name) VALUES (48, 'Texas');
INSERT INTO alias (data_id, alias_name) VALUES (48, 'UT');
INSERT INTO alias (data_id, alias_name) VALUES (49, 'Yeshiva');
INSERT INTO alias (data_id, alias_name) VALUES (50, 'GW');
INSERT INTO alias (data_id, alias_name) VALUES (50, 'GWU');
INSERT INTO alias (data_id, alias_name) VALUES (50, 'George Washington');
INSERT INTO alias (data_id, alias_name) VALUES (51, 'Rensselaer');
INSERT INTO alias (data_id, alias_name) VALUES (51, 'RPI');
INSERT INTO alias (data_id, alias_name) VALUES (52, 'The Tulane University of Louisiana');
INSERT INTO alias (data_id, alias_name) VALUES (52, 'Tulane');
INSERT INTO alias (data_id, alias_name) VALUES (52, 'TU');
INSERT INTO alias (data_id, alias_name) VALUES (53, 'BU');
INSERT INTO alias (data_id, alias_name) VALUES (54, 'Fordham');
INSERT INTO alias (data_id, alias_name) VALUES (55, 'OSU');
INSERT INTO alias (data_id, alias_name) VALUES (55, 'Ohio State');
INSERT INTO alias (data_id, alias_name) VALUES (55, 'Buckeyes');
INSERT INTO alias (data_id, alias_name) VALUES (56, 'Pepperdine');
INSERT INTO alias (data_id, alias_name) VALUES (57, 'University of Maryland, College Park');
INSERT INTO alias (data_id, alias_name) VALUES (57, 'University of Maryland at College Park');
INSERT INTO alias (data_id, alias_name) VALUES (57, 'UM');
INSERT INTO alias (data_id, alias_name) VALUES (57, 'UMD');
INSERT INTO alias (data_id, alias_name) VALUES (57, 'UMCP');
INSERT INTO alias (data_id, alias_name) VALUES (57, 'Maryland');
INSERT INTO alias (data_id, alias_name) VALUES (58, 'A&M');
INSERT INTO alias (data_id, alias_name) VALUES (58, 'Texas A&M');
INSERT INTO alias (data_id, alias_name) VALUES (58, 'TAMU');
INSERT INTO alias (data_id, alias_name) VALUES (58, 'Aggies');
INSERT INTO alias (data_id, alias_name) VALUES (59, 'UConn');
INSERT INTO alias (data_id, alias_name) VALUES (60, 'Florida');
INSERT INTO alias (data_id, alias_name) VALUES (60, 'UF');
INSERT INTO alias (data_id, alias_name) VALUES (60, 'U of F');
INSERT INTO alias (data_id, alias_name) VALUES (61, 'Pitt');
INSERT INTO alias (data_id, alias_name) VALUES (62, 'Northeastern');
INSERT INTO alias (data_id, alias_name) VALUES (62, 'NU');
INSERT INTO alias (data_id, alias_name) VALUES (63, 'Purdue');
INSERT INTO alias (data_id, alias_name) VALUES (64, 'Southern Methodist');
INSERT INTO alias (data_id, alias_name) VALUES (64, 'SMU');
INSERT INTO alias (data_id, alias_name) VALUES (65, 'Syracuse');
INSERT INTO alias (data_id, alias_name) VALUES (65, '''Cuse');
INSERT INTO alias (data_id, alias_name) VALUES (65, 'SU');
INSERT INTO alias (data_id, alias_name) VALUES (66, 'Georgia');
INSERT INTO alias (data_id, alias_name) VALUES (66, 'UGA');
INSERT INTO alias (data_id, alias_name) VALUES (67, 'Worcester');
INSERT INTO alias (data_id, alias_name) VALUES (67, 'WPI');
INSERT INTO alias (data_id, alias_name) VALUES (68, 'Clemson');
INSERT INTO alias (data_id, alias_name) VALUES (69, 'Rutgers, The State University of New Jersey');
INSERT INTO alias (data_id, alias_name) VALUES (69, 'Rutgers');
INSERT INTO alias (data_id, alias_name) VALUES (70, 'University of Minnesota, Twin Cities');
INSERT INTO alias (data_id, alias_name) VALUES (70, 'U of M');
INSERT INTO alias (data_id, alias_name) VALUES (71, 'BYU');
INSERT INTO alias (data_id, alias_name) VALUES (71, 'The Y');
INSERT INTO alias (data_id, alias_name) VALUES (72, 'Michigan State');
INSERT INTO alias (data_id, alias_name) VALUES (72, 'MSU');
INSERT INTO alias (data_id, alias_name) VALUES (73, 'UI');
INSERT INTO alias (data_id, alias_name) VALUES (73, 'Iowa');
INSERT INTO alias (data_id, alias_name) VALUES (73, 'Hawkeyes');
INSERT INTO alias (data_id, alias_name) VALUES (74, 'Virginia Tech');
INSERT INTO alias (data_id, alias_name) VALUES (74, 'VT');
INSERT INTO alias (data_id, alias_name) VALUES (75, 'Baylor');
INSERT INTO alias (data_id, alias_name) VALUES (76, 'CSM');
INSERT INTO alias (data_id, alias_name) VALUES (76, 'Mines');
INSERT INTO alias (data_id, alias_name) VALUES (77, 'IU Bloomington');
INSERT INTO alias (data_id, alias_name) VALUES (77, 'IU');
INSERT INTO alias (data_id, alias_name) VALUES (77, 'Indiana');
INSERT INTO alias (data_id, alias_name) VALUES (77, 'Indiana University');
INSERT INTO alias (data_id, alias_name) VALUES (78, 'UA');
INSERT INTO alias (data_id, alias_name) VALUES (78, 'Alabama');
INSERT INTO alias (data_id, alias_name) VALUES (79, 'University of California, Santa Cruz');
INSERT INTO alias (data_id, alias_name) VALUES (79, 'UC Santa Cruz');
INSERT INTO alias (data_id, alias_name) VALUES (79, 'Santa Cruz');
INSERT INTO alias (data_id, alias_name) VALUES (79, 'UCSC');
INSERT INTO alias (data_id, alias_name) VALUES (80, 'Delaware');
INSERT INTO alias (data_id, alias_name) VALUES (80, 'UD');
INSERT INTO alias (data_id, alias_name) VALUES (81, 'Tulsa University');
INSERT INTO alias (data_id, alias_name) VALUES (81, 'Tulsa');
INSERT INTO alias (data_id, alias_name) VALUES (81, 'TU');
INSERT INTO alias (data_id, alias_name) VALUES (82, 'American');
INSERT INTO alias (data_id, alias_name) VALUES (82, 'AU');
INSERT INTO alias (data_id, alias_name) VALUES (83, 'Auburn');
INSERT INTO alias (data_id, alias_name) VALUES (83, 'AU');
INSERT INTO alias (data_id, alias_name) VALUES (84, 'Marquette');
INSERT INTO alias (data_id, alias_name) VALUES (85, 'SUNY ESF');
INSERT INTO alias (data_id, alias_name) VALUES (85, 'ESF');
INSERT INTO alias (data_id, alias_name) VALUES (86, 'Denver');
INSERT INTO alias (data_id, alias_name) VALUES (86, 'DU');
INSERT INTO alias (data_id, alias_name) VALUES (87, 'University of Vermont and State Agricultural College');
INSERT INTO alias (data_id, alias_name) VALUES (87, 'UVM');
INSERT INTO alias (data_id, alias_name) VALUES (87, 'Vermont');
INSERT INTO alias (data_id, alias_name) VALUES (88, 'Drexel');
INSERT INTO alias (data_id, alias_name) VALUES (88, 'DU');
INSERT INTO alias (data_id, alias_name) VALUES (89, 'Stevens');
INSERT INTO alias (data_id, alias_name) VALUES (90, 'State University of New York at Binghamton');
INSERT INTO alias (data_id, alias_name) VALUES (90, 'Binghamton');
INSERT INTO alias (data_id, alias_name) VALUES (90, 'Bing');
INSERT INTO alias (data_id, alias_name) VALUES (90, 'BU');
INSERT INTO alias (data_id, alias_name) VALUES (91, 'Miami');
INSERT INTO alias (data_id, alias_name) VALUES (91, 'Miami U');
INSERT INTO alias (data_id, alias_name) VALUES (91, 'Miami of Ohio');
INSERT INTO alias (data_id, alias_name) VALUES (91, 'MU');
INSERT INTO alias (data_id, alias_name) VALUES (92, 'St. Louis University');
INSERT INTO alias (data_id, alias_name) VALUES (92, 'SLU');
INSERT INTO alias (data_id, alias_name) VALUES (92, 'Saint Louis');
INSERT INTO alias (data_id, alias_name) VALUES (92, 'St. Louis');
INSERT INTO alias (data_id, alias_name) VALUES (93, 'Mizzou');
INSERT INTO alias (data_id, alias_name) VALUES (93, 'MU');
INSERT INTO alias (data_id, alias_name) VALUES (93, 'University of Missouri–Columbia');
INSERT INTO alias (data_id, alias_name) VALUES (93, 'Missouri');
INSERT INTO alias (data_id, alias_name) VALUES (94, 'Clark');
INSERT INTO alias (data_id, alias_name) VALUES (95, 'University of Colorado Boulder');
INSERT INTO alias (data_id, alias_name) VALUES (95, 'CU-Boulder');
INSERT INTO alias (data_id, alias_name) VALUES (95, 'CU');
INSERT INTO alias (data_id, alias_name) VALUES (95, 'Boulder');
INSERT INTO alias (data_id, alias_name) VALUES (95, 'Colorado');
INSERT INTO alias (data_id, alias_name) VALUES (96, 'University of Massachusetts');
INSERT INTO alias (data_id, alias_name) VALUES (96, 'UMass');
INSERT INTO alias (data_id, alias_name) VALUES (96, 'Massachusetts');
INSERT INTO alias (data_id, alias_name) VALUES (96, 'UMass Amherst');
INSERT INTO alias (data_id, alias_name) VALUES (97, 'Iowa State University of Science and Technology');
INSERT INTO alias (data_id, alias_name) VALUES (97, 'Iowa State');
INSERT INTO alias (data_id, alias_name) VALUES (97, 'ISU');
INSERT INTO alias (data_id, alias_name) VALUES (98, 'Texas Christian');
INSERT INTO alias (data_id, alias_name) VALUES (98, 'TCU');
INSERT INTO alias (data_id, alias_name) VALUES (99, 'University of California, Riverside');
INSERT INTO alias (data_id, alias_name) VALUES (99, 'UCR');
INSERT INTO alias (data_id, alias_name) VALUES (99, 'UC Riverside');
INSERT INTO alias (data_id, alias_name) VALUES (100, 'USD');
INSERT INTO alias (data_id, alias_name) VALUES (100, 'San Diego');


